### ISSUE TITLE
Node.js installation prerequisites

### ISSUE THREAD

**Issue by kfrajtak** [Softmotions/ejdb#105]
Do I really have to have VS.NET installed to install EJDB node.js module? I have VS.NET 2013, I had to install VS.NET 2010 and VC++ tools and still I can't install EJDB module:

```
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.t
argets(48,5): error MSB8020: The build tools for Visual Studio 2010 (Platform T
oolset = 'v100') cannot be found. To build using the v100 build tools, please i
nstall Visual Studio 2010 build tools.  Alternatively, you may upgrade to the c
urrent Visual Studio tools by selecting the Project menu or right-click the sol
ution, and then selecting "Upgrade Solution...". [C:\projects\node.js\ejdb\node
_modules\ejdb\build\ejdb_native.vcxproj]
```

Can you make a module distribution without the native compilation? 

Thanks,
Karel

**Comment by tyutyunkov** [comment]
Hello, Karel!
We publish some binary distributions of ejdb-node for Windows systems. Now you can try to install ejdb for node by `npm install ejdb`. 
If binary distribution for your combination of system architecture and node version is not published, npm will build it from sources again. In this case please tell us next information: system architecture, node and npm version and we will try to publish binaries for you.
