### ISSUE TITLE
Python setup does not compile on OSX due to link to rt.

### ISSUE THREAD

**Issue by fjmalass** [Softmotions/ejdb#106]
When using 
Apple LLVM version 5.0 (clang-500.2.79) (based on LLVM 3.3svn)
Target: x86_64-apple-darwin13.0.0
Thread model: posix
on MacOSX 10.9.1
--
python setup.py install 
crashes at linking with rt library.
---
the 
kwargs["libraries"].append("rt")
should be removed from setup.py/EJDBPythonExt/__init__

Hope this will not have adverse effects in the future.

**Comment by adamansky** [comment]
fixed
