### ISSUE TITLE
Cross compile fails

### ISSUE THREAD

**Issue by dtoubelis** [Softmotions/ejdb#108]
I'm trying cross-compile _tcejdb_ on 32-bit platform for x86_64 platform and it doesn't work. The problem is that _gcc_ trying to use 32-bit version of stdlib.h header which does not exist in the target toolchain. So, I suspect that target host detection is not working properly.

Here are parameters that passed to _configure_ script:

```
./configure \
		--target=x86_64-timesys-linux-gnu \
		--host=x86_64-timesys-linux-gnu \
		--build=i686-linux-gnu \
--prefix=/usr \
--exec-prefix=/usr \
		--bindir=/usr/bin \
		--sbindir=/usr/sbin \
		--libdir=/usr/lib \
		--libexecdir=/usr/lib \
		--sysconfdir=/etc \
		--datadir=/usr/share \
		--localstatedir=/var \
		--mandir=/usr/share/man \
		--infodir=/usr/share/info \
		--includedir=/usr/include \
		--enable-devel
```

**Comment by adamansky** [comment]
It should be fixed now. See https://github.com/Softmotions/ejdb/blob/master/INSTALL
