### ISSUE TITLE
$orderby -1 Bug

### ISSUE THREAD

**Issue by jbeejones** [Softmotions/ejdb#110]
Hi, if you run the following script with node it will produce a segmentation fault.
The bug only produces if $orderby -1 value is used and if the value property in records vary from "9855" to 9855 (i.e. Integer and String mixed) .
(tested with EJDB CLI v1.1.12-0).

Output from script here:

    shell$ node ejdb_sortbug.js 
    OK  3
    Segmentation fault: 11

Script code here:

      // ejdb $orderby bug
      var EJDB = require("ejdb");
      var conn = EJDB.open("orderbybugdb", EJDB.DEFAULT_OPEN_MODE);

    var dataset = [
    {
        "comment": "One", 
        "status": "New", 
        "xversion": 0, 
        "value": 9855, 
        "title": "Lead 0"
    }, 
    {
        "comment": "Two", 
        "status": "New", 
        "xversion": 0, 
        "value": "18973", 
        "title": "Lead 1"
    }, 
    {
        "comment": "Three", 
        "status": "New", 
        "xversion": 0, 
        "value": "25504", 
        "title": "Lead 2"
    }
    ];

    conn.save("mycoll", dataset, function(err, res) {
	if (err) {
		console.error("ERR ", err);
	} else {
		console.log("OK ", res.length);
		getData();
	}
    });

    function getData(){
	conn.find("mycoll", {}, {"$orderby":{"value":-1}}, function(err, cursor, count) {
		try {
			if (err) {
				console.log("ERROR BAD ",err);
			} else {
				console.log("Found ", count);
				
				while (cursor.next()) {
					console.log(cursor.object().value);
				}
				cursor.close();
				
			}
		} catch (findex) {
			console.log("EXCEPTION FIND", findex);
		}
	});	
    }

By the way, thanks for good work and a great product :)

**Comment by mydatacards** [comment]
Hi, thanks for fixing bugs :)
When will I be able to download a new version of EJDB-node where this fix is in effect?

/Jon Erik

**Comment by adamansky** [comment]
Just published in npm repo

**Comment by jbeejones** [comment]
Thanx ;)

/Jon Erik
