### ISSUE TITLE
Execute queries on resultset

### ISSUE THREAD

**Issue by elendilm** [Softmotions/ejdb#116]
Hello, I am here for the first time. I saw this project and is very interested in it. I would like to deveop a wrapper for Qt and Qml framework. I was just playing with this for the last 2 days. I thought it would be very good if there was a way to execute queries on resultset that are already queried (kind of like an in-memory search). 
It would greatly help in implementing ejdb with Qt's model view so that we can signal changes  when data is  updated or added to model without again re-executing the query on the full database.

Is there any way of accomplishing it already. 
Also why is there no $push implemented. it seems like a basic necessity. The only way (of which I am aware of) the basic $push can now be implemented is via $addToSet with uniqueKey/value appended to data.

**Comment by adamansky** [comment]
Depends on #130

**Comment by adamansky** [comment]
Closed in favour to ejdb 2.0 https://github.com/Softmotions/ejdb/blob/master/README.md
