### ISSUE TITLE
ejdbsavebson after indexing doesn't show up in ejdbqryexecute

### ISSUE THREAD

**Issue by elendilm** [Softmotions/ejdb#117]
For about 10 million data,
building an index on "name" with  JBIDXSTR  took 183661 milliseconds (approx 3 minutes) to complete
and then doing a search on it completes in 0-5 milli seconds.
This is all very good. But calling savebson after indexing doesn't include the new row in index and therefore only returns the old results. I have to explicitly again rebuild the index which again takes upto 3 minutes to return the newly added rows. Is there any way to save while updating index.

**Comment by adamansky** [comment]
Ok. I'm investigating this behaviour. Are you using C API?

**Comment by elendilm** [comment]
Yes. I am using the C library

**Comment by elendilm** [comment]
It doesn't have to be millions of data. It can be reproduced by saving just one or two records,  index them, save another record and search returns only the first two.

**Comment by adamansky** [comment]
Added test case: 4fa54c0 it works as expected. Can you provide simple test case?

**Comment by elendilm** [comment]
I tested it again. I couldn't reproduce the issue and to my astonishment it works as expected. Anyways I will close this issue for now.
