### ISSUE TITLE
Wildcard String matching

### ISSUE THREAD

**Issue by elendilm** [Softmotions/ejdb#118]
This might seem a bit silly, but I couldn't find a way to do this.
consider a collection with a record  {name: "harry"}
querying for {name: "*arr*"} must return the record. How can we do this. Is there any support for such matching queries?

**Comment by kkk777kkk** [comment]
use bson_append_regex

**Comment by elendilm** [comment]
Thanks. It worked. 

I was using json2bson function for converting json string to bson. It seems you can't use that for regex values. Is it planned to include regex inside json2bson when it detects regex values. It would help very much. Manually generating bson is very cumbersome.
