### ISSUE TITLE
New EJDB version can not be compiled "easily" on systems which have older versions of gcc and now cmake is required

### ISSUE THREAD

**Issue by obourdon** [Softmotions/ejdb#121]
I used to compile the shared library on CentOS 6.6 systems and Fedora 10 (I know it is very old but ...) and now the build mechanism requires cmake >= 2.8 (2.6 on Fedora 10) and  GCC version must be at least 4.7! (4.4 on CentOS 6.6)

I can very well agree that for Fedora 10 this is not relevant as this system is way out of date
However CentOS 6.6 is the latest RHEL based free OS so compilation should work (and it worked previously as I got libtcejdb.so.9.11.0 which was working very well few weeks back

**Comment by adamansky** [comment]
I've tested with `cmake_policy(VERSION 2.6)` + GCC compiler restriction was removed
