### ISSUE TITLE
New EJDB version does not build on MacOSX

### ISSUE THREAD

**Issue by obourdon** [Softmotions/ejdb#122]
Here is the output of the following commands

mkdir build ; cd build ; cmake -DCMAKE_BUILD_TYPE=Release ../ ; make
<pre>
[ 44%] Building C object src/CMakeFiles/ejdb.dir/ejdb/ejdbutl.c.o
Linking C shared library libejdb.dylib
Undefined symbols for architecture x86_64:
  "___atomic_add_fetch", referenced from:
      _tchdbfbpinsert in tchdb.c.o
  "___atomic_load_n", referenced from:
      _tchdbput in tchdb.c.o
      _tchdbputkeep in tchdb.c.o
      _tchdbputcat in tchdb.c.o
      _tchdbout in tchdb.c.o
      _tchdbaddint in tchdb.c.o
      _tchdbadddouble in tchdb.c.o
      _tchdbputproc in tchdb.c.o
      ...
  "___atomic_store_n", referenced from:
      _tchdbftruncate2 in tchdb.c.o
ld: symbol(s) not found for architecture x86_64
clang: fatal error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/libejdb.1.2.4.dylib] Error 1
make[1]: *** [src/CMakeFiles/ejdb.dir/all] Error 2
make: *** [all] Error 2
</pre>

$ uname -a
Darwin macbook-home 12.6.0 Darwin Kernel Version 12.6.0: Wed Dec 17 19:11:40 PST 2014; root:xnu-2050.48.15~1/RELEASE_X86_64 x86_64
$ gcc --version
i686-apple-darwin11-llvm-gcc-4.2 (GCC) 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11.00)
$ cmake --version
cmake version 3.1.3

**Comment by adamansky** [comment]
Hi Olivier! Please attach the full build log. It seems `clang` used as compiler. I'm working for osx build env, hope I'll fix it shortly.

**Comment by obourdon** [comment]
Hello Anton, thanks for looking into this. You can get the full output of the commands from
http://www.olivierbourdon.com/EJDB (sorry did not find out how to attach files to issue/comment
Just let me know if you need something else

**Comment by adamansky** [comment]
Please reopen it if you have problems

**Comment by obourdon** [comment]
Works like a charm thanks for the fix
