### ISSUE TITLE
$addToSet works improperly for non existent nested keys.

### ISSUE THREAD

**Issue by elendilm** [Softmotions/ejdb#123]
document {abc: {  } }
$addToSet: { de: {key: value} }
results in      {abc: {  }, de: [{key: value}] }        // Ok

document {abc: { de: [] } }
$addToSet: { 'abc.de': {key: value} }
results in      {abc: { de: [{key: value}] } }          // Ok

document {abc: {  } }
$addToSet: { 'abc.de': {key: value} }
results in    {abc: {  }, de: [{key: value}] }        // Improper functionality

**Comment by adamansky** [comment]
It seems this issue been fixed in v1.2.6 (current master). Reopen it if you have problems.
