### ISSUE TITLE
cross compile  EJDB for MIPS

### ISSUE THREAD

**Issue by SurajSinha** [Softmotions/ejdb#125]
Hi, 

I am trying to cross compile EJDB and when it tries to link jbhmgr it gets error
Linking C executable jbhmgr
../../libejdb-1.a(tchdb.c.o): In function `tchdbftruncate2':
tchdb.c:(.text+0x820): undefined reference to `__atomic_load_8'
tchdb.c:(.text+0x9c4): undefined reference to `__atomic_store_8'
../../libejdb-1.a(tchdb.c.o): In function `tchdbseekread2':
tchdb.c:(.text+0x1254): undefined reference to `__atomic_load_8'
../../libejdb-1.a(tchdb.c.o): In function `tchdbseekwrite2':
tchdb.c:(.text+0x2a90): undefined reference to `__atomic_load_8'
tchdb.c:(.text+0x2bf8): undefined reference to `__atomic_load_8'
collect2: error: ld returned 1 exit status

How can this problem be solved?

**Comment by adamansky** [comment]
The source of this problem resides in   [myconf.h](https://github.com/Softmotions/ejdb/blob/master/src/myconf.h.in#L533) due to erroneous compiller (atomic API) detection.

Please let me know the exact version of your compiller and platform.

**Comment by SurajSinha** [comment]
It is a mips gcc compiler version 4.7.2

**Comment by adamansky** [comment]
Please check the latest master sources, this issue should be fixed by  52c5a3e

**Comment by SurajSinha** [comment]
Thanks it is working.
What did u change?

**Comment by adamansky** [comment]
It seems on 32bit MIPS  `__atomic_load_n` and `__atomic_store_n` are unsupported for 64bit wide values. The actual changes I've made: 52c5a3e
