### ISSUE TITLE
Is there anything to be considered while using threads to access the database  collections?

### ISSUE THREAD

**Issue by elendilm** [Softmotions/ejdb#126]
In the main thread, I use ejdbopen(db, "database", JBOWRITER | JBOCREAT);
Then from other threads I call ejdbcreatequery and ejdbqryexecute. Is it the proper way of using it?

**Comment by adamansky** [comment]
Hi! Yes, within the single process you can use ejdb API from multiple threads.  If you have some issues please let us know.
