### ISSUE TITLE
Queries of int64_t (longs) on Windows is returning invalid results

### ISSUE THREAD

**Issue by achoy** [Softmotions/ejdb#127]
I'm running EJDB on Windows 7 Pro and storing BSON objects with long values > 2^32.  When I attempt to query, I am not getting any results that have those long values if I attempt to query for them. 

Example:

int64_t timems;
bson_init_as_query(&bq1);
timems = 4294967397;  // <-- large numbers > 2^32 does not work
bson_append_long(&bq1, "atm", timems);
bson_finish(&bq1);
q1 = ejdbcreatequery(jb, &bq1, NULL, 0, NULL);
res = ejdbqryexecute(coll, q1, &count, 0, NULL);

I tested the same code and data tables in Linux (Ubuntu 14.04) and that properly returns. Is there any issues with longs (int64_t) on Windows?

**Comment by adamansky** [comment]
Hi Albert! We're invesitigating this issue. I hope we'll fix it within few days. Thank you)

**Comment by achoy** [comment]
Hello Adam, after a long investigation, it looks like the problem is _parse_qobj_impl() function in ejdb.c.

Under the BSON_LONG case. there is a conversion from int64_t value back into string using:

around line 5038 ejdb.c:

qf.expr = tcsprintf("%ld", qf.exprlongval);

That doesn't convert int64_t value when running on Windows, it only handle 32 bit value:

so the way to do it is:

qf.expr = tcsprintf("%" PRId64, qf.exprlongval);

That format string is already used in bson_print_raw() function.  Here is the Wikipedia reference: 
[Wikipedia](http://en.wikipedia.org/wiki/Printf_format_string)

That seems to fix the problem.  I also noticed that in nxjson.h the struct nx_json is using "long" type instead of int64_t.

**Comment by achoy** [comment]
Submitted pull request #128 with suggested changes.

**Comment by adamansky** [comment]
Thank you Albert! Your fix been merged into master.

**Comment by adamansky** [comment]
I need to review ejdb code for this kind of problems
