### ISSUE TITLE
Enhancement: support querying symbols (BSON_SYMBOL) like strings (BSON_STRING)

### ISSUE THREAD

**Issue by achoy** [Softmotions/ejdb#129]
Our dev team would like to be able to use BSON_SYMBOL as an additional datatype to store and query. EJDB currently handles symbols like strings (in reading/writing) but have no support to query for symbols. The querying logic for strings can be extended to also deal with symbols in the same way. 

I would like to propose our implementation of that enhancement.   It will provide all the string matching query functions to also work with symbol objects.  We have tested a patched EJDB version (1.1.25) with equality and $in comparisons successfully.    Would like to see if that can be added to EJDB library.  Feedback welcome. Will submit a pull request (to patch 1.2.6) when ready.

**Comment by adamansky** [comment]
Fixed by #132
