### ISSUE TITLE
EJDB not saving records on disk

### ISSUE THREAD

**Issue by SurajSinha** [Softmotions/ejdb#134]
I executed the sample program and after that i ran this program to print the saved records but it says 
Records found : 0

Why isn't anything being saved?

#include "ejdb.h"
#include <locale.h>

static EJDB *jb;

int main() {
    setlocale(LC_ALL, "en_US.UTF-8");
    jb = ejdbnew();
    if (!ejdbopen(jb, "addressbook", JBOWRITER | JBOCREAT | JBOTRUNC)) {
        return 1;
    }

    //Get or create collection 'contacts'
    EJCOLL *coll = ejdbcreatecoll(jb, "contacts", NULL);

    //Now select one record.
    //Query: {'name' : {'$begin' : 'Bru'}} //Name starts with 'Bru' string
    bson bq1;
    bson_init_as_query(&bq1);
    bson_append_start_object(&bq1, "name");
    bson_append_string(&bq1, "$begin", "Bru");
    bson_append_finish_object(&bq1);
    bson_finish(&bq1);
    EJQ *q1 = ejdbcreatequery(jb, &bq1, NULL, 0, NULL);

    uint32_t count;
    TCLIST *res = ejdbqryexecute(coll, q1, &count, 0, NULL);
    fprintf(stderr, "\n\nRecords found: %d\n", count);

    for (int i = 0; i < TCLISTNUM(res); ++i) {
        void *bsdata = TCLISTVALPTR(res, i);
        bson_print_raw(bsdata, 0);
    }
    fprintf(stderr, "\n");

    //Dispose result set
    tclistdel(res);

    //Dispose query
    ejdbquerydel(q1);
    bson_destroy(&bq1);

    //Close database
    ejdbclose(jb);
    ejdbdel(jb);
    return 0;
}

**Comment by adamansky** [comment]
Please consider `JBOTRUNC` option

**Comment by SurajSinha** [comment]
When should i use JBOTRUNC?

**Comment by adamansky** [comment]
If you're using `JBOTRUNC` flag a database will be truncated (deleted) on opening.

**Comment by SurajSinha** [comment]
Adamansky thanks for quick help. 
I am trying to use this database in my thesis project. I was wondering if it is possible to do random access on arrays saved inside the documents. Currently i am using an iterator.

**Comment by adamansky** [comment]
[BSON] (http://bsonspec.org/) based on serial processing of data. You need to store bson documents in some other format or use an [array database indexes](https://github.com/Softmotions/ejdb/blob/master/src/ejdb/ejdb.h#L348) for querieing data in arrays.
