### ISSUE TITLE
json2bson can't handle float data type

### ISSUE THREAD

**Issue by liuaiping** [Softmotions/ejdb#140]
The following codes: 
        bson *bsondata = NULL;
        const char *data = "{x:420.98}";
        bsondata = json2bson(data);
        
Then i used the bson2json to print the bsondata, but the result is 
      "x" : '..--).0-*(+,))+(0(.00000

**Comment by adamansky** [comment]
Seems it fixed already (#135) in the `master` branch. Please, check that you are using latest version from git master.

**Comment by liuaiping** [comment]
Thanks.This problem had fixed.
