### ISSUE TITLE
File size limitation

### ISSUE THREAD

**Issue by renatofj** [Softmotions/ejdb#142]
I have a collection (data set) with a lot of data and i am facing a problem with the file size: when it reaches exactly 2Gb, my system freezes and it isn't else possible insert data.

I am running the latest EJDB x64 version (1.2.7) with C# binding. I am not sure, but maybe the problem is the use of 32 bits variables (uint32).

Anyone can help me?

Thansk & Regards,

**Comment by adamansky** [comment]
Hi! What version of C# binding you are using? I'm trying to reproduce your issue

**Comment by renatofj** [comment]
Hi !

Sorry...i am using the last version of C# binding.

I solved my problem by splitting the collection in parts, but i think would be better to fix this limitation.

**Comment by adamansky** [comment]
Fixed in #149
