### ISSUE TITLE
bson names conflict

### ISSUE THREAD

**Issue by dmigous** [Softmotions/ejdb#145]
Hello

My project already uses libbson https://api.mongodb.org/libbson/current/index.html

But, ejdb has inside as I see some modified version of libbson. Because ejdb::bson has a bit different function signatures and types I cannot move completely to ejdb::bson in whole project. I just wanted to serialize data using libbson and taking from it raw bson data buffer create ejdb::bson type and put it into db, and vice versa. But there are name conflicts. Is it possible to add to all bson related stuff some prefix like `ejdb_`, what do you think ? Maybe I can prepare patch for it.

**Comment by adamansky** [comment]
Hello! Renaming bson methods will break compatibility with various `libejdb` clients, so it highly undesirable :(

**Comment by dmigous** [comment]
hmm, yes you are right. Then maybe in major version release it is possible.

**Comment by rennhak** [comment]
+1

**Comment by elendilm** [comment]
+1

**Comment by adamansky** [comment]
Closed in favour to ejdb 2.0 https://github.com/Softmotions/ejdb/blob/master/README.md
