### ISSUE TITLE
The query failed and clean the db

### ISSUE THREAD

**Issue by liuaiping** [Softmotions/ejdb#146]
#include <ejdb/ejdb.h>

static EJDB *jb;

void testAddData(void);

void testQuery27(void);

void testQuery27(void) 
{ //$exists
    EJCOLL *contacts = ejdbcreatecoll(jb, "contacts", NULL);
    
    bson bsq1;
    bson_init_as_query(&bsq1);
    bson_append_start_object(&bsq1, "address.room");
    bson_append_bool(&bsq1, "$exists", true);
    bson_append_finish_object(&bsq1);
    bson_finish(&bsq1);
    

    EJQ *q1 = ejdbcreatequery(jb, &bsq1, NULL, 0, NULL);
    

    uint32_t count = 0;
    TCXSTR *log = tcxstrnew();
    TCLIST *q1res = ejdbqryexecute(contacts, q1, &count, 0, log);
    printf("testQuery27 count = %d\n", count);

    bson_destroy(&bsq1);
    tclistdel(q1res);
    tcxstrdel(log);
    ejdbquerydel(q1);
}

int main(int argc, char *argv[]) 
{
   
    jb = ejdbnew();
    if (!ejdbopen(jb, "test", JBOWRITER | JBOCREAT | JBOTRUNC)) {
        printf("ejdbopen failed.\n");
        return -1;
    }
      
    testQuery27();   //count = 0
    ejdbclose(jb);

    testAddData();
    testQuery27();   //count = 1
    ejdbclose(jb);
    
    return 0;
}

void testAddData(void) 
{
    jb = ejdbnew();
    if (!ejdbopen(jb, "test", JBOWRITER | JBOCREAT | JBOTRUNC)) {
        return;
    }
    bson_oid_t oid;
    EJCOLL *ccoll = ejdbcreatecoll(jb, "contacts", NULL);

    //Record 1
    bson a1;

    bson_init(&a1);
    bson_append_start_object(&a1, "address");
    bson_append_string(&a1, "city", "Novosibirsk");
    bson_append_string(&a1, "country", "Russian Federation");
    bson_append_string(&a1, "zip", "630090");
    bson_append_string(&a1, "street", "Pirogova");
    bson_append_int(&a1, "room", 334);
    bson_append_finish_object(&a1); //EOF address

    bson_finish(&a1);
    ejdbsavebson(ccoll, &a1, &oid);
    bson_destroy(&a1);

}

The first time , the testQuery27 print count = 0.
But the second time , the testQuery27  print count = 1

Why????????

**Comment by liuaiping** [comment]
Who can help me? i had spent one day to see this problem and i didn't have any ideas!!!!!

**Comment by liuaiping** [comment]
What is the difference ?

**Comment by adamansky** [comment]
Hello! 

1.) You opened the empty db, so testQuery27() == 0
2) Database closed
3) Database opened
4) The new record added by `testAddData`
5) testQuery27() fetched that record so prints `1`

**Comment by liuaiping** [comment]
@adamansky , but when run the send time(The db has data now) , but the result is same. This was what i asked. So why?

**Comment by adamansky** [comment]
You open the database with `JBOTRUNC` flag means all data will be erased when db opens

**Comment by liuaiping** [comment]
@adamansky   
L.O.L...    Speechless to mysel.  

Thanks.
