### ISSUE TITLE
Implement mongodb $setOnInsert

### ISSUE THREAD

**Issue by liuaiping** [Softmotions/ejdb#147]
Question 1. 
     When the collection is empty, i used the "$set" like this:
               bson bsq1;
               bson_init_as_query(&bsq1);
               bson_append_start_object(&bsq1, "$set");  //"$upsert"
               bson_append_string(&bsq1, "name", "john");
               bson_append_finish_object(&bsq1);
               bson_finish(&bsq1);

The above codes will not create a record in the collection(Because the collection is empty). But when i used the "$upsert" and it work. It means i should query the collection to know whether the collection is empty and then i can know the operation is "$set" or "$upsert". Right?   I think it is very tedious. So it is a bug?

**Comment by elendilm** [comment]
They are two different features.

If you don't know whether john is in the database and add John with age: 10 if he does not exist in the database or update his age if he exists , then use $upsert.
 
If you just want to update john's age ONLY if he exists, then use $set.

**Comment by liuaiping** [comment]
@elendilm ,
Question : "If you don't know whether john is in the database and add John with age: 10 if he does not exist in the database or update his age if he exists , then use $upsert."  
           For example , my data struct is like:

          {
  "name": "Jhon",
  "info": {
    "age": 26,
    "address": "Us",
    "parents": {
      "fa": {
        "name": "Jhon",
        "age": 47
      }
    }
  }
}
Now i only want to update the age and i can not use "$upsert", becase the "$upsert" will not handle the "." and i should use the $set. So i had to query the db.Right? Can you tell me how can i do with this case?

I hope you can see this problem, @adamansky . Thanks!

**Comment by elendilm** [comment]
It appears $upsert cannot be used the way $set can is used with nested keys. Docs say that $upsert does not behave the way mongodb $setOnInsert does. So basically what you are asking for is a $setOnInsert or $upsert with nested key support.

**Comment by elendilm** [comment]
If $setOnInsert is really what you are asking for, then please change the title to something like "Implement mongodb $setOnInsert".

**Comment by adamansky** [comment]
Closed in favour to ejdb 2.0 https://github.com/Softmotions/ejdb/blob/master/README.md
