### ISSUE TITLE
$set fails to create nested keys if supplied with a non existent topmost key

### ISSUE THREAD

**Issue by liuaiping** [Softmotions/ejdb#148]
The follow codes:
     ejdb>db.aipi.update({"$set":{"info.name.par.age":40, "info.name.mot.age":40}})
But the result was:
     >{info: { name: { mot: { age: 40 } } } }

The "par" was not created. Why ?

Second, i want to update the age to 50, like this:
ejdb> db.aipi.update({"$set":{"info.name.mot.age":56}})
the result was :    Segmentation fault (core dumped)        

If i used the c interface and the result was i couldn't operate the "info.name.mot" anymore.

**Comment by elendilm** [comment]
I just tested this and can confirm that it is a bug.
If there is no key named 'a' then
-----------------------------------------
the bug OCCURS in {"$set":{"a.b.c.d":50, "a.f.g.h":50}}
but DOES NOT occur when updated with {"$set":{"a.b.c.d":50, "e.f.g.h":50}}

If there is a topmost key named 'a':  { } then
--------------------------------------------------------
The bug no longer occurs when updated with {"$set":{"a.b.c.d":50, "a.f.g.h":50}}.

So I think it may have something to do with the topmost non existent key.

**Comment by elendilm** [comment]
Could you change the title to something like "$set fails to create nested keys if supplied with a non existent topmost key" or something  like that.

**Comment by liuaiping** [comment]
@elendilm  Thanks,Sure.

**Comment by adamansky** [comment]
Thank you very much! Hope will fix it shortly.
