### ISSUE TITLE
Not able to store data above 2GB! Help!

### ISSUE THREAD

**Issue by sherry-ummen** [Softmotions/ejdb#149]
Hi,

Tried to stores some quite large data. and I reached to a point of 2Gb of file sixe after that the process just hung. When I stop it and start again then i get StackOverFlowexception from EJB.cs

internal static bool _ejdbopen(IntPtr db, string path, int mode) {
IntPtr pptr = Native.NativeUtf8FromString(path); //UnixMarshal.StringToHeap(path, Encoding.UTF8);
try {
return _ejdbopen(db, pptr, mode);
} finally {
Marshal.FreeHGlobal(pptr); //UnixMarshal.FreeHeap(pptr);
}
}

At this particular line: return _ejdbopen(db, pptr, mode);

**Comment by akaustel** [comment]
What file system do you use? Could that be the limit? I'm fairly sure that I have been able to handle data sets larger than 2GB.

**Comment by sherry-ummen** [comment]
Windows 8.1 NTFS


C# Driver


What I tried:


var stopwatch = new Stopwatch();
            stopwatch.Start();
            //int COLLECTIONNAME = 1;
            foreach (var index in Enumerable.Range(1, 1000000000)) {
                var customer = BSONDocument.ValueOf(new {
                    Id = "FOOBAR" + index,
                    name = "FOOBAR" + index,
                    date = DateTime.Now.ToLocalTime().Millisecond,
                    records = Enumerable.Range(1, 100000).ToArray(),
                    rep_modified = "M",
                    split = false,
                    type = 0,
                    user = "ADMI",
                    version = "A"
                });
                jb.Save("parrots", customer);
            
            }
            stopwatch.Stop();
            Console.WriteLine("Speed: " + stopwatch.ElapsedMilliseconds);






Sent from Windows Mail





From: akaustel
Sent: ‎Wednesday‎, ‎July‎ ‎1‎, ‎2015 ‎9‎:‎30‎ ‎PM
To: Softmotions/ejdb
Cc: Sherry Ummen





What file system do you use? Could that be the limit? I'm fairly sure that I have been able to handle data sets larger than 2GB.

**Comment by akaustel** [comment]
Have you set the large option?

`  bool large;         /**< Large collection. It can be larger than 2GB. Default false */`

I do not know how to set it in C#, but I guess you can figure that out.

**Comment by sherry-ummen** [comment]
Yes, Did that 

 EJDBCollectionOptionsN co = new EJDBCollectionOptionsN();
            co.large = true;
            co.compressed = false;
            jb.EnsureCollection("parrots", co);
            var stopwatch = new Stopwatch();
            stopwatch.Start();
            foreach (var index in Enumerable.Range(1, 1000000000)) {
                var customer = BSONDocument.ValueOf(new {
                    Id = "FOOBAR" + index,
                    name = "FOOBAR" + index,
                    date = DateTime.Now.ToLocalTime().Millisecond,
                    records = Enumerable.Range(1, 100000).ToArray(),
                    rep_modified = "M",
                    split = false,
                    type = 0,
                    user = "ADMI",
                    version = "A"
                });
                jb.Save("parrots", customer);
            }
            stopwatch.Stop();
            Console.WriteLine("Speed: " + stopwatch.ElapsedMilliseconds);

But still after reavhing to the point of 2Gb the process just hangs.

**Comment by akaustel** [comment]
Did you remove the database file or see to that the large option really was enabled. It might not be updated on an already existing db file.

**Comment by sherry-ummen** [comment]
Yes I always create a new database. How can I check from the file that it has that flag ON?

Thanks

Sent from my Windows Phone
________________________________

**Comment by akaustel** [comment]
The method `DBMeta` seems familiar from the `nodejs` API. It returns a BSONDocument.

Found in https://github.com/Softmotions/ejdb-csharp/blob/master/Ejdb.DB/EJDB.cs:

```c#
public class EJDB : IDisposable {
    ...
    public BSONDocument DBMeta
    ...
```

**Comment by akaustel** [comment]
Please consider rephrasing your title. Some might read it as arrogant and disregard your plea for help altogether.

**Comment by sherry-ummen** [comment]
I have changed the title as you suggested! Thanks

**Comment by sherry-ummen** [comment]
now I tried to check the properties as you said and it is actually a 'large' file. Here is the snapshot
![image](https://cloud.githubusercontent.com/assets/2572380/8479677/ee10b904-20e1-11e5-9a9a-0a2366ba87e4.png)

To show whats happenign I prepared to videos:
1) https://www.youtube.com/watch?v=Y_98eRAwbgs&feature=youtu.be
This one if you see its writting to the file and when it reaches to 2Gb it automatically becomes 1Gb may be some clearing EJDB does and then again after reaching 2GB it just hang their forever

2) https://www.youtube.com/watch?v=tAe-y9VehjY&feature=youtu.be
this shows that when you open the same hung database then we get Stackover flow exception.

**Comment by adamansky** [comment]
Hello!! Thank you for this detailed report! I will investigate this problem within few days, hope fix it ASAP

**Comment by sherry-ummen** [comment]
Thank you for your response. I had almost lost faith on this project :).

Btw it would be nice if you could comment on this also https://github.com/Softmotions/ejdb/issues/150

Thanks

**Comment by adamansky** [comment]
Ok, I'm suspecting this problem related to the maximal size of [MapViewOfFile](https://msdn.microsoft.com/en-us/library/windows/desktop/aa366761%28v=vs.85%29.aspx) address space. 2GB? (correct me if I'm wrong) See [tchdb.c#L5689)](https://github.com/Softmotions/ejdb/blob/master/src/tchdb/tchdb.c#L5689). TokyoCabinet's TCHDB windows port uses mmaping of whole database file. Looking for hooks to bypass it.

**Comment by sherry-ummen** [comment]
mine is a 64bit system

**Comment by sherry-ummen** [comment]
does you current change fix the problem? somewhow I can test this?

**Comment by adamansky** [comment]
Fixed
v1.2.9 released http://ejdb.org/doc/install/windows.html 
Please reopen issue if you have troubles.

**Comment by sherry-ummen** [comment]
NIce! Thanks its works. I just tested by insertting 10Gb of data
