### ISSUE TITLE
Feature request!. please allow different process to access same database simultaneously.

### ISSUE THREAD

**Issue by sherry-ummen** [Softmotions/ejdb#150]
Atleast it should be configurable. So that whoever wants can use it for others they by default they cannot.

It would be great help for my project.

Thanks

**Comment by akaustel** [comment]
Accessing the db files from multiple processes raises problems with performance, synchronization among other things. Would #85 solve you problem? Running the database in one process and allow queries to that process from multiple other processes.

**Comment by sherry-ummen** [comment]
Performance is users headache. I just wanted to have the possiblity to have a configurable option something like "MultiProcess" which means that it can be used by multiple process.

And about the perfromance it depends on the how much data is written or read. We have a simple database we use with our standalone application which locks the file while write, and we use it multiple process we see some degradation of performance but really not much since the read and write is super fast.

About #85 that issue was created on 2013 I don't even know whether it was ever taken care of :) but coming to the point TCP/IP layer slows down things also. We are now using mongodb; after profillign we find that we spend lot of time on network calls itself.

And we use it in local client system so speed should be quite good enough. Hope I was clear in what I wanted to say  :)

**Comment by sherry-ummen** [comment]
Any updates on this please? Thanks

**Comment by adamansky** [comment]
Closed in favour to ejdb 2.0 https://github.com/Softmotions/ejdb/blob/master/README.md
