### ISSUE TITLE
why no pkg-config for APPLE ?

### ISSUE THREAD

**Issue by dmigous** [Softmotions/ejdb#152]
Sorry for bother. 
Why do not create .pc file for Apple. 

My use case is I cross-compile ejdb under Linux host for iOS arm and use ejdb via dependency through Autotools, where very convenient to use macro PKG_CHECK_MODULES to pull dependencies.

Hence interesting why
```
if (NOT APPLE AND NOT BUILD_FRAMEWORK)
        configure_file(${CMAKE_CURRENT_SOURCE_DIR}/libejdb.pc.in ${EJDB_GENERATED_DIR}/libejdb.pc @ONLY)
        install(FILES ${EJDB_GENERATED_DIR}/libejdb.pc DESTINATION ${CMAKE_INSTALL_LIBDIR}/pkgconfig)
endif(NOT APPLE AND NOT BUILD_FRAMEWORK)
```

**Comment by rennhak** [comment]
+1

**Comment by rennhak** [comment]
Thank you!

**Comment by dmigous** [comment]
Thanks! :smile:
