### ISSUE TITLE
Can't open DB after some time (~20 min)

### ISSUE THREAD

**Issue by GiulianoFranchetto** [Softmotions/ejdb#153]
Hi,
we are using ejdb to store logs. Everything is working fine during the first 20 minutes, and then this error occurs :
ERROR:/......../src/tchdb/tchdb.c:403:tchdbopen:-:1:threading error:0:Success
If we stop the program and start it again, the crash disappears, and comes back ~20min after ...
Do you have any idea of what it's happening?

Regards

**Comment by adamansky** [comment]
Please ensure you are calling `ejdbdel()` after `ejdbclose()`

**Comment by GiulianoFranchetto** [comment]
thanks, i indeed forgot ejdbdel() !
