### ISSUE TITLE
Compress mode not work on ARM

### ISSUE THREAD

**Issue by liuaiping** [Softmotions/ejdb#154]
I installed the ejdb on ARM. And in my codes, i had set the ejdbcreatecoll used the compress mode. But it like that the data was not compressed. On my PC, the same codes does the compress but it was not work on ARM.
                         ARM:
                                     1.5M      test_db
                                     1.9M      test_db_collection1
                        PC:
                                      520K     test_db
                                      988K     test_db_collection1
But if i copy the files on ARM to the PC. And then used the ejdb command to open them. And quit. The size of the files had decrease!!! They become 520K and 988K. Why?

**Comment by adamansky** [comment]
Closed in favour to ejdb 2.0 https://github.com/Softmotions/ejdb/blob/master/README.md
