### ISSUE TITLE
Cross compile failed

### ISSUE THREAD

**Issue by liuaiping** [Softmotions/ejdb#158]
/home/cacti/mxe$ make MXE_TARGETS='x86_64-w64-mingw32.static i686-w64-mingw32.static'
[build]     pkgconf              x86_64-w64-mingw32.static                                               

Failed to build package pkgconf for target x86_64-w64-mingw32.static!
------------------------------------------------------------
configure: creating ./config.status
config.status: creating Makefile
config.status: creating tests/run.sh
config.status: error: cannot find input file: `config.h.in'
make[1]: *** [build-only-pkgconf_x86_64-w64-mingw32.static] Error 1
make[1]: Leaving directory `/home/cacti/mxe'
real	0m4.059s
user	0m3.326s
sys	0m0.795s
------------------------------------------------------------
[log]      /home/cacti/mxe/log/pkgconf_x86_64-w64-mingw32.static

make: *** [/home/cacti/mxe/usr/x86_64-w64-mingw32.static/installed/pkgconf] Error 1

Why?

**Comment by adamansky** [comment]
Hi! It seems the problem in mxe environment. Please remove the `/home/cacti/mxe/` folder and ensure you have completed all steps in this guide http://ejdb.org/doc/install/building.html#building-native-windows-libs 
Hope it helps

**Comment by liuaiping** [comment]
@adamansky , I had tried again. But the error was same.

/home/cacti/mxe$ nano ./settings.mk
/home/cacti/mxe$ cat settings.mk 
JOBS := 1
MXE_TARGETS := x86_64-w64-mingw32.static i686-w64-mingw32.static
LOCAL_PKG_LIST := winpthreads pcre zlib lzo bzip2 cunit
.DEFAULT local-pkg-list:
local-pkg-list: $(LOCAL_PKG_LIST)

/home/cacti/mxe$ make
[check requirements]
[download]  pkgconf                                                                                      
[build]     pkgconf              x86_64-w64-mingw32.static                                               

Failed to build package pkgconf for target x86_64-w64-mingw32.static!
------------------------------------------------------------
configure: creating ./config.status
config.status: creating Makefile
config.status: creating tests/run.sh
config.status: error: cannot find input file: `config.h.in'
make[1]: *** [build-only-pkgconf_x86_64-w64-mingw32.static] Error 1
make[1]: Leaving directory `/home/cacti/mxe'
real	0m4.002s
user	0m3.323s
sys	0m0.752s
------------------------------------------------------------
[log]      /home/cacti/mxe/log/pkgconf_x86_64-w64-mingw32.static

make: *** [/home/cacti/mxe/usr/x86_64-w64-mingw32.static/installed/pkgconf] Error 1

**Comment by liuaiping** [comment]
@adamansky , my system info is: 

Linux cacti-virtual-machine 3.16.0-34-generic #45~14.04.1-Ubuntu SMP Tue Mar 24 11:14:29 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by adamansky** [comment]
Very strange..

Please ensure you have all required packages installed:

```sh
sudo apt-get install   \
autoconf automake autopoint bash bison bzip2 cmake flex  \
gettext git g++ gperf intltool libffi-dev libtool   \
libltdl-dev libssl-dev libxml-parser-perl make openssl   \
p7zip-full patch perl pkg-config python ruby scons sed   \
unzip wget xz-utils 
```

```
~/tmp$ git clone https://github.com/mxe/mxe.git 
Cloning into 'mxe'...
..
Checking connectivity... ready.
cd ./mxe
nano ./settings.mk
make 
[check requirements]
[download]  pkgconf                                                                                      
[build]     pkgconf              x86_64-w64-mingw32.static                                               
[done]      pkgconf              x86_64-w64-mingw32.static                                1436 KiB       0m4.842s
...
```

**Comment by liuaiping** [comment]
@adamansky , I'm sure that i had installed the packages. What's your system?

**Comment by adamansky** [comment]
```
lsb_release -d
Description:	Ubuntu 15.04
```

**Comment by adamansky** [comment]
x64

**Comment by liuaiping** [comment]
Ok. I will install 15.04. But it was really strangely .

**Comment by liuaiping** [comment]
@adamansky . Good! I had installed the mxe environment. But when i build the ejdb.  The error was :

cacti@cacti-virtual-machine:~/Documents/ejdb/build-win32$ cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=../win64-tc.cmake ..
-- Using project changelog file: /home/cacti/Documents/ejdb/Changelog
Wine executable not found! Failed to initiate wintools staff.
CMake Warning at src/CMakeLists.txt:64 (message):
  Library 'librt' not FOUND


-- Could NOT find LibLZMA (missing:  LIBLZMA_INCLUDE_DIR LIBLZMA_LIBRARY LIBLZMA_HAS_AUTO_DECODER LIBLZMA_HAS_EASY_ENCODER LIBLZMA_HAS_LZMA_PRESET) 
-- Lzo includes and libraries NOT found. 
CMake Error at src/CMakeLists.txt:206 (add_w32_importlib):
  Unknown CMake command "add_w32_importlib".


-- Configuring incomplete, errors occurred!

What's the add_w32_importlib?

**Comment by adamansky** [comment]
```
>> Wine executable not found! Failed to initiate wintools staff.
```

You need to install the `wine`: `sudo apt-get install wine`
Although this requirement is not mentioned in docs

**Comment by liuaiping** [comment]
@adamansky .Thanks , i had compiled the libejdb.dll and libejdb.lib success.  When i used them in my visual studio 2013 project.  My program crash!  Here are my codes:

void testfunc()
{
	const char *data = "{\"name\":\"cacti\"}";
	bson * payload = json2bson(data);
	char *wbuf = NULL;
	int wsiz = 0;

	bson bq;
	bson_init_as_query(&bq);
	bson_append_bson(&bq, "upsert", payload);
	bson_finish(&bq);

	if (bson2json(bson_data(&bq), &wbuf, &wsiz) == BSON_OK) {
		printf("%s\n", wbuf);   //Had print out
		free(wbuf);    //Crash at this porint   !!!!!
	}

	bson_del(payload);

testejdb.exe has griggered a breakpoint. When i click the continue, the detail error info was:

DebugAddertion Failed!
Expression:_CrtIsValidHeapPointer(pUserData)

I thought that on windows the heap memory was corrupt!
......
