### ISSUE TITLE
Crash on windows 

### ISSUE THREAD

**Issue by liuaiping** [Softmotions/ejdb#159]
I compiled the libejdb.dll and libejdb.lib (Follow guide http://ejdb.org/doc/install/building.html#building-native-windows-libs )success. When i used them in my visual studio 2013 project. My program crash! Here are my codes:

void testfunc()
{
const char *data = "{\"name\":\"cacti\"}";
bson \* payload = json2bson(data);
char *wbuf = NULL;
int wsiz = 0;

bson bq;
bson_init_as_query(&bq);
bson_append_bson(&bq, "$upsert", payload);
bson_finish(&bq);

if (bson2json(bson_data(&bq), &wbuf, &wsiz) == BSON_OK) {
    printf("%s\n", wbuf);   //Had print out
    free(wbuf);    //Crash at this porint   !!!!!
}

bson_del(payload);

The visual studio popup a windows:
testejdb.exe has griggered a breakpoint. 

When i click the continue, the detail error info was:

DebugAddertion Failed!
Expression:_CrtIsValidHeapPointer(pUserData)

Do i need do other things before i using the libejdb.dll.

And  the second thing is what do the files lib.exe and link.exe ? 
......

**Comment by adamansky** [comment]
Could you send me whole msvc solution directory archived as `.zip` to: adamansky@softmotions.com

**Comment by liuaiping** [comment]
@adamansky . I had sent the whole solution to you.

**Comment by liuaiping** [comment]
@adamansky . I had sent the whole solution to you.

**Comment by adamansky** [comment]
I've published instructions how to start with MSVC and EJDB please follow this guide
and everything will be fine. http://ejdb.org/doc/install/msvc.html

**Comment by vessler** [comment]
Problem is about using different runtime. ejdb library allocates memory using MSVCRT.DLL (in call bson2json). When freeing this memory from user application created in VisualStudio 2013 (for example) we call free() function from MSVC120.DLL. As seems to me this calls are incompatible so we have a crash.

**Comment by vessler** [comment]
Still you can use bson_free to free memory allocated by bson2json. But, you should build ejdb with mxe by yourself because there is no bson_free exported by library from site.

**Comment by adamansky** [comment]
Closed in favour to ejdb 2.0 https://github.com/Softmotions/ejdb/blob/master/README.md
