### ISSUE TITLE
Unable to build with CMake 2.6

### ISSUE THREAD

**Issue by akaustel** [Softmotions/ejdb#168]
The required version of CMake is 2.6 in the CMakeLists.txt, but GNUInstallDirs module is not present in 2.6 or 2.8.8 which I tested. I finally installed 3.3 and everything went smooth. I suggest the required version should be changed, to which version exactly I do not know, maybe someone else knows.

**Comment by adamansky** [comment]
Closed in favour to ejdb 2.0 https://github.com/Softmotions/ejdb/blob/master/README.md
