### ISSUE TITLE
Support more data types in query

### ISSUE THREAD

**Issue by uranusjr** [Softmotions/ejdb#171]
Currently you can save anything into EJDB, but the query supports only some of the data types, while others are dropped. This is particularly inconvenient with `$upsert`, since some of the data will be lost comparing to `ejdbsavebson`.

It would be nice if support for at least `BSON_BINDATA` and `BSON_TIMESTAMP` can be added. Or at the very least, `ejdbcreatequery` should fail explicitly with invalid BSON data types. Dropping them (silently!) leads to queries not working as they should and data not being saved. This can be quite surprising and produce bugs.

**Comment by adamansky** [comment]
Closed in favour to ejdb 2.0 https://github.com/Softmotions/ejdb/blob/master/README.md
