### ISSUE TITLE
$elemMatch syntax

### ISSUE THREAD

**Issue by 0x4eadac43** [Softmotions/ejdb#172]
Let`s consider a document:

``` json
{
    "name": "Andy",
    "childs": [
        { "name": "Garry", "age": 2 },
        { "name": "Sally", "age": 4 }
    ]
}
```

Following query doesn`t count the document (using the driver):

``` json
{
    "$and": [
        { "name": "Andy" },
        { "childs": { 
            "$elemMatch": { 
                "$and": [ 
                    { "name": "Sally" }, 
                    { "age": 4 } 
                ] 
            } 
        } } 
    ] 
}
```

Is it bug or by design?
P.S. It works fine with MongoDB.

**Comment by tyutyunkov** [comment]
This is not a bug. To correct the query just remove inward $and operator like this (a document will be selected if and only if it matches to each given clause): 
```
{
    "$and": [
        { "name": "Andy" },
        { "childs": { 
            "$elemMatch": { 
                    "name": "Sally", 
                    "age": 4
            } 
        } } 
    ] 
}
```

You could find more information on EJDB query language at [EJDB Doc#elemMatch](http://ejdb.org/doc/ql/ql.html#elemmatch)
