### ISSUE TITLE
Comparison on strings

### ISSUE THREAD

**Issue by restdbio** [Softmotions/ejdb#173]
I am not sure if this is a bug, but I'm able to get results from this query in MongoDB and not in EJDB against the same data collection:

{name:{$gte:"john"}}

I see from the documentation that the comparison operators only work for numbers in EJDB. Would it be difficult to implement this for strings as well?

**Comment by adamansky** [comment]
Closed in favour to ejdb 2.0 https://github.com/Softmotions/ejdb/blob/master/README.md
