### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by aaiyer** [Softmotions/ejdb#179]
Is this project still maintained? I am trying to decide if I should use this library for a new project, but as there has been no commits for a year or more, want to ask if this project is still alive?

**Comment by akaustel** [comment]
You and me, both! This is a really useful database, but I have not seen much activity here. I am mostly working with the nodejs version (i.e. EJDB built as a node plugin).

**Comment by aaiyer** [comment]
I am unsure why this project is being left idle, the commercial potential for this project is enormous...

**Comment by akaustel** [comment]
It would be nice to hear from @adamansky, @fyudanov or @tyutyunkov what the state of EJDB is.

**Comment by wgerven** [comment]
+1

**Comment by adamansky** [comment]
Hi guys! Ejdb is not abandoned! But we are quite burdened with another project and feeling a lack of time. However our team is growing and in near future we will continue support of this project. Currently I’m thinking toward to ejdb2 – a complete reimplementation which will be designed to avoid many limitations of ejdb, I’m going to share some thoughts about ejdb2 and hope for discussion and community support.

**Comment by tudorels** [comment]
It's good to see the project is not abandoned. I hope to see you soon working on this project, because I want to use it in some other projects. Thank you!
