### ISSUE TITLE
Impossible to download or cross build Windows binaries

### ISSUE THREAD

**Issue by bawNg** [Softmotions/ejdb#181]
I can't download any Windows binaries because http://softmotions.com/ejdb/ no longer exists, all links to windows binaries point to http://softmotions.com/ejdb/archives/, and there are no mirrors.

I also can't cross compile from a linux box because the CMake build script relies on downloading files from https://softmotions.com/windev/ which no longer exists.

```
~/git/ejdb/build-win32$ make package
[  2%] Generating ../WINTOOLS/link.exe
https://softmotions.com/windev/link.exe:
2017-02-20 23:03:40 ERROR 404: (no description).
src/CMakeFiles/wintools_init.dir/build.make:62: recipe for target 'WINTOOLS/link.exe' failed
```

Ejdb would be a great fit for a new open source project I'm working on but Windows compatibility is required.

**Comment by adamansky** [comment]
Ok, I see. I will fix it shortly

**Comment by adamansky** [comment]
Fixed, it should be ok now.
