### ISSUE TITLE
building error 

### ISSUE THREAD

**Issue by denisdemaisbr** [Softmotions/ejdb#184]
linux distribution: Ubuntu 14.04.5 LTS 

$ uname -a
Linux controlpos 2.6.32-042stab123.1 #1 SMP Wed Mar 22 15:21:30 MSK 2017 x86_64 x86_64 x86_64 GNU/Linux
$ git clone https://github.com/Softmotions/ejdb
$ cd ejdb
$ mkdir build
$ cd build
$ cmake -DCMAKE_BUILD_TYPE=Release ../
-- Using project changelog file: /root/ejdb/Changelog
CMake Error at cmake/Modules/EjdbUtils.cmake:8 (message):
  ejdb requires an out of source build.
Call Stack (most recent call first):
  CMakeLists.txt:55 (macro_ensure_out_of_source_build)

-- Configuring incomplete, errors occurred!
See also "/root/ejdb/CMakeFiles/CMakeOutput.log".
$ cmake --version
cmake version 2.8.12.2

**Comment by adamansky** [comment]
Closed in favour to ejdb 2.0 https://github.com/Softmotions/ejdb/blob/master/README.md
