### ISSUE TITLE
$pull not working as in MongoDB

### ISSUE THREAD

**Issue by restdbio** [Softmotions/ejdb#192]
$pull works fine to remove elements from a simple array. However, when I try to remove elements from an array containing objects, it seems to be required to have an exact match with the whole object. I'm sure this is not intended because it would be very difficult to create correct queries (this works on MongoDB)

Example data:
```
{ _id: '59392dcd7e1bee3800000000',
  name: 'adam',
  favoritecolors: 
   [ { id: 1, color: 'blue' },
     { id: 3, color: 'yellow' } ] }
{ _id: '59392def7e1bee3800000001',
  name: 'ansky',
  favoritecolors: 
   [ { id: 1, color: 'blue' },
     { id: 2, color: 'red' } ] }
```

This query does not pull out anything:
```
db.update("pullcoll", {$pull:{"favoritecolors":{"color":"blue"}}}
```
but this one does:
```
db.update("pullcoll", {$pull:{"favoritecolors":{"id":1, "color":"blue"}}}
```
If I change the order of the properties, there's not any luck either:
```
db.update("pullcoll", {$pull:{"favoritecolors":{"color":"blue","id":1}}}
```

**Comment by adamansky** [comment]
Closed in favour to ejdb 2.0 https://github.com/Softmotions/ejdb/blob/master/README.md
