### ISSUE TITLE
DB looks broken occasionally

### ISSUE THREAD

**Issue by briancui** [Softmotions/ejdb#194]
Hello,

We have a program using ejdb as the datastore, but occasionally the DB was broken, we don't know the root cause and how to reproduce it. 

ejdb> db.open('findit_probe_db')
{ file: '/home/cisco/findit_probe_db',
  collections: 
   [ { name: 'data',
       file: '/home/cisco/findit_probe_db_data',
       records: 15,
       options: 
        { buckets: 294911,
          cachedrecords: 0,
          large: false,
          compressed: true },
       indexes: [] } ] }
ejdb> db.getDBMeta()
{ file: '/home/cisco/findit_probe_db',
  collections: 
   [ { name: 'data',
       file: '/home/cisco/findit_probe_db_data',
       records: 15,
       options: 
        { buckets: 294911,
          cachedrecords: 0,
          large: false,
          compressed: true },
       indexes: [] } ] }
From above, we know that there are 15 records, however I can't query any record as below:

ejdb> db.find('data')
Found 0 records

Returned cursor:
{ pos: 0,
  length: 0,
  close: [Function: close],
  reset: [Function: reset],
  hasNext: [Function: hasNext],
  next: [Function: next],
  field: [Function: field],
  object: [Function: object] }
ejdb> 

I attached db files, appreciate if you can help to analysis what's wrong in the db and in what situation it will cause the problem.

Thanks,
Brian
[db.zip](https://github.com/Softmotions/ejdb/files/1124391/db.zip)

**Comment by adamansky** [comment]
Closed in favour to ejdb 2.0 https://github.com/Softmotions/ejdb/blob/master/README.md
