### ISSUE TITLE
tcfdb Segmentation Faults 2017-07-23

### ISSUE THREAD

**Issue by rwhitworth** [Softmotions/ejdb#195]
Hello, I was using American Fuzzy Lop (afl-fuzz) to fuzz input to the `tcfdb` program on Linux. Is fixing the crashes from these input files something you're interested in? The input files can be found here: https://github.com/rwhitworth/ejdb-fuzz/tree/master/2017-07-23-tcfdb-list

The files can be executed as `./tcfdb list id_filename` to cause seg faults.  One looks to be a legit issue while the other is a failed assertion that is probably lower priority.  I compiled the debug version of the program.

Let me know if I can provide any more information to help narrow down this issue.

**Comment by adamansky** [comment]
Closed in favour to ejdb 2.0 https://github.com/Softmotions/ejdb/blob/master/README.md

**Comment by adamansky** [comment]
Closed in favour to ejdb 2.0 https://github.com/Softmotions/ejdb/blob/master/README.md
