### ISSUE TITLE
file can't open with unfined error

### ISSUE THREAD

**Issue by lzyun** [Softmotions/ejdb#198]
Meet the problem when open database, does anyone has the same experience?

Broken database file Link
[https://www.dropbox.com/sh/ee9nmxsqgwsm9d2/AACm5LCabB1_Pb8AwXljWDdoa?dl=0](url)

![screen shot 2017-09-05 at 10 38 24 am](https://user-images.githubusercontent.com/6794886/30042822-6b803bf0-9226-11e7-9c29-b0deb490d5c2.png)

**Comment by adamansky** [comment]
Closed in favour to ejdb 2.0 https://github.com/Softmotions/ejdb/blob/master/README.md
