### ISSUE TITLE
Security vulnerabilities impacting ejdb

### ISSUE THREAD

**Issue by cve-reporting** [Softmotions/ejdb#203]
Hello,

Our security research team has found multiple security vulnerabilities impacting ejdb.
As this are sensitive security issues, this message is to request a direct contact email and a PGP key for further communication.

Please acknowledge receipt of this bug submission, so we can confirm that we reached correct person for reporting security issues or forward this message to interested person.

**Comment by userabuser** [comment]
Hi @adamansky — did anything come of this? I see the OP has made a couple other sec-reports as issues in other repos but was unsure of the validity of this one or whether this has been addressed behind the scenes.

**Comment by adamansky** [comment]
Closed in favour to ejdb 2.0 https://github.com/Softmotions/ejdb/blob/master/README.md
