### ISSUE TITLE
EJDB2 Flutter binding

### ISSUE THREAD

**Issue by adamansky** [Softmotions/ejdb#242]
* https://github.com/flutter/flutter/issues/7053
* https://github.com/dart-lang/sdk/issues/34452
* #239  
* #241

**Comment by taliptako** [comment]
this would be awesome i think it would be so fast to use this in flutter

**Comment by om-ha** [comment]
Good day @adamansky ,

Care about outside contribution?

If yes I can start with [your first comment](https://github.com/Softmotions/ejdb/issues/242#issue-431028946) and see where that leads.

**Comment by adamansky** [comment]
Thank you  @om-ha ! It will be very helpful to do some progress for iOS. I plan release Android binding in upcoming Monday

**Comment by adamansky** [comment]
I don't consider to use `dart ffi` since it still not supports async callbacks even in current tech preview.

**Comment by om-ha** [comment]
> Thank you @om-ha ! It will be very helpful to do some progress for iOS. I plan release Android binding in upcoming Monday

My background is iOS but now I'm developing flutter apps. So my contributions here would be focused around dart/flutter and iOS-specific code.
I'll start bit by bit and give it my best.

> I don't consider to use `dart ffi` since it still doesn't support async callbacks even in current tech preview. @om-ha
I see, so instead of `dart ffi` you're directly interoperating with dart using Asynchronous Native Extensions of the Dart VM. Correct?

**Comment by adamansky** [comment]
Not quite right - flutter has different interoperating technology: https://flutter.dev/docs/development/platform-integration/platform-channels

**Comment by adamansky** [comment]
https://pub.dev/packages/ejdb2_flutter

**Comment by om-ha** [comment]
Congrats! Will try to add iOS support soon.

Will create an iOS platform channel by replicating your work in [Android's Platform Channel](https://github.com/Softmotions/ejdb/blob/master/src/bindings/ejdb2_flutter/android/src/main/java/com/softmotions/ejdb2/EJDB2Plugin.java).
