### ISSUE TITLE
Where can I find old (1.x) docs?

### ISSUE THREAD

**Issue by uranusjr** [Softmotions/ejdb#252]
All links in previous documentation are now 404. While I’m very excited about EJDB2, we still have software running on 1.x and need to look up those docs (especially the query language part to extract data out of them).

**Comment by adamansky** [comment]
HI! No problem. Please checkout https://github.com/Softmotions/ejdb/tree/ejdb_1.x_docs 
You can open index.html in browser.

**Comment by uranusjr** [comment]
Thanks! Here’s the rendered page (with htmlpreview.github.io) for anyone else that needs it:

https://htmlpreview.github.io/?https://raw.githubusercontent.com/Softmotions/ejdb/ejdb_1.x_docs/doc/ql/ql.html
