### ISSUE TITLE
Patches available for MacOs Yosemite

### ISSUE THREAD

**Issue by supertwang** [Softmotions/ejdb#256]
After much hand-patching I was finally able to compile this on MacOS Yosemite.  I'm happy to share the patched files (most from the iowow distro that get downloaded as part of the build process), and notes, if anyone else wants to attempt this, or if one of the maintainers wants to fix it in the source.  FWIW, I don't know cmake at all, so rather than try to learn it, I had to hand-patch the downloaded files after the iowow distro downloads, and the build fails.  I hope this helps someone, it was a pita to figure out!  The library looks great though, and hopefully the effort is "Worth it".  Contact me if you're interested.

**Comment by adamansky** [comment]
Hi! Thank you a lot for your efforts! Could you please send patched files to  `adamansky @ gmail dot com` or create a pull request to iowow project https://github.com/Softmotions/iowow

**Comment by supertwang** [comment]
Hi Adam.

Thanks for caring enough about your software to fold these in!  To me its a great sign I’ve found a good library and developer that I can base my own software on.  Kudos!  I’m attaching the files and my notes to myself, since I don’t know git/cmake very well.  I hope they help!  To find my changes, you’ll have to diff these with the originals.

The library looks great!

Best, 
Dave

**Comment by adamansky** [comment]
Thank you Dave! Will close this issue as soon as patches will be applied in 2-3 days.

**Comment by adamansky** [comment]
Hi! Pushed an update in `master` branch.

Had resolved issues with `clock_gettime` for `osx < 10.12`
Also set `static_assert` to `_Static_assert` if it is not defined previously, hope it will fix issues with yosemite.

* https://github.com/Softmotions/ejdb/commit/2caad351625debbc6933c951e770b80a06cafe44
* https://github.com/Softmotions/iowow/commit/fe50e49e5f0d96267c60e8b3a2522a80dd98aecc

Please reopen this issue if problems will remain
