### ISSUE TITLE
WAL config + K8s readWriteMany

### ISSUE THREAD

**Issue by 1N50MN14** [Softmotions/ejdb#259]
Hey @adamansky,

First of all thank you very much for all the effort you put into ejdb, finally a no-nonsense embeddable database that I can actually use in production.

Two questions:
1. Since ejdb is built atop iowow I figured there must be a way to configure write ahead log options (I need to decrease save point timeout to 1-2 seconds) but couldn't find any documentation on how to accomplish that. I'm intending to use the Dart client, the only documented constructor option that I found was `truncate`.

2. Since you're check pointing data would it be safe to run multiple concurrent writers on the same file? My use case is multiple k8s pods with access to shared (high performance) nfs volume. I noticed you used isolates in one of the Dart examples, hence my question if I'm able to run writers on the same file within completely separate processes (each with its own dart "isolates").

Thank you

**Comment by adamansky** [comment]
Hi Ayman! 

1. Take a look to [all options](https://github.com/Softmotions/ejdb/blob/master/src/bindings/ejdb2_dart/lib/ejdb2_dart.dart#L284 ) you may set on database opening. Named argument `wal_savepoint_timeout_sec`:  specifies a number of seconds between wal save-points. Save-point sematic described [here](http://iowow.io/wal). So to decrease save point timeout to 1 seconds   you need set `wal_savepoint_timeout_sec` parameter  to `1` (minimal allowed value) 

2. EJDB2 supports *many reader/writer threads within a single process* but no access from multple OS processes.  Dart isolate represents dedicated isolate thread as part DartVM process, so it is no problem to use EJDB from multiple isolates. To keep data consistency access to WAL & database file is guarded by thread mutexes and won't performed concurrently. I most use  scenarios writes will not be a performance bottleneck since these ops are short lived.

@1N50MN14

**Comment by 1N50MN14** [comment]
Thank you very much for the reply @adamansky this was very helpful, I noticed you also have a `readonly` flag, which takes me back to follow up on point 2, with a different approach this time:

As far as running EJDB2 in my scenario it will always run within multiple isolated processes (pods) with auto-scaling enabled both vertically (dynamic memory and cpu allocation) and horizontally (auto-spawned across multiple machines), the cluster size itself is also dynamic, both nodes and pods running in isolated processes can be added or shut down at any given time, sometimes (rarely) SIGTERM won't make it through before the underlying machine is killed. 

The above infrastructure makes embedded + WAL perfect for my use case, I'll be able to manually acknowledge writes (using a message broker) otherwise queue up failed writes and retry. Worst case scenario would be 1s worth of data loss and I'm fine with that. 

My approach here would be to keep it simple and scale shared storage, similar to the above, instead of dealing with sharding, replication and what not on a software level. 

Given the above as well as your feedback do you believe the following would be feasible:
1. Assuming X number of collections/files I will run exactly X number of isolated *write-only* single processes (for example 0.5 vcpu each), this way I can separately scale writes in the future on collection bases.

2. Multiple readers within multiple processes <-- here I'm not sure of how ejdb2 keeps metadata up to date for readers. Very often I don't even mind a 1 second lag in data consistency (specially when it comes to logs).

My queries are mostly either reads or writes excepting for a few in which case I can write a simple wrapper around writes to commit those remotely.

I hope this can work... thanks again and apologies for the lengthy response (I'm planning to spend next week on this).

**Comment by adamansky** [comment]
Hey Ayman!

1. We have only two ways to deal writes from separate _OS processes_
  1.1 Use EJDB instances for every process isolated from each-other. 
        It may be good solution in some use cases, for example we use separated per-process ejdb instances for every market instrument in our trading platform. It provides a great scalability for us. But one big drawback - ejdb instances are isolated from each other in any sense.
  1.2 Communicate from external OS processes to one particular processes with embedded ejdb (using network, ipc, etc..). Here we have a single dataset and able access to all data from multiple processes communicating to particular data-holder process. 

2. EJDB operates within a single process but uses many threads for IO. Writes to database are protected by classical Reader-Writer locks (https://en.wikipedia.org/wiki/Readers%E2%80%93writer_lock) So if you have high writers ratio over reades it may be performance bottleneck here.

So please consider you requirements again. I'm feeling ejdb is not the best choice for your architecture with high write ops from multiple processes.  Anyway thank you for your interest!)

**Comment by 1N50MN14** [comment]
Hey @adamansky just a quick shout out to let you know I've been playing around a bit with the different approaches I believe (1) + increase WAL just a bit more from 1 sec would work for my use case. I'm going to test some more proper real life scenarios. 

In the meantime I'm just dropping this message to to thank you again for taking the time to explain to me (I did some additional homework, now I *get* it) and for EJDB itself! 

By the way the technical scenario I was describing was identical to this: https://github.com/facebook/rocksdb/issues/908
