### ISSUE TITLE
Indexing strings in an array or map

### ISSUE THREAD

**Issue by akaustel** [Softmotions/ejdb#271]
EJDB 1 supported array indexes, which I used to make really fast lookups ~20ms for a collection with 4M documents. Is this possible in EJDB 2? I tried to make a string index for `words`:

```javascript
{ words: ['quite', 'impressive', 'speed'] }
```

But I could not figure out how to query it to see if the index works or not. In EJDB 1 I did:

```javascript
db.find({ words: { $strand: keywords } }, () => ...)
```

**Comment by akaustel** [comment]
Figured out the EJDB 2 query:

```javascript
await db.createQuery('@collection/words/[** in ["impressive", "speed"]]').list();
```

But still unsure about the index.

**Comment by akaustel** [comment]
Figured out the index. I had created my index using unique string index (0x05), which did not work with the array. Changing to non-unique string index fixed the issue (0x04).

In node i changed:

```js
await db.ensureStringIndex('collection', '/words', true);
```

to 

```js
await db.ensureStringIndex('collection', '/words');
```

**Comment by adamansky** [comment]
👍
