### ISSUE TITLE
ARM & X86 32bit

### ISSUE THREAD

**Issue by AngusWooster** [Softmotions/ejdb#274]
Hi
Can ejdb support arm and x86 32bit platform ?

Sincerely

**Comment by adamansky** [comment]
Hi! Yes x86-32 and arm32 are supported. Feel free to reopen this ticket if you have questions

**Comment by AngusWooster** [comment]
Hi 
I am appreciated for your prompt reply.
I have tried ejdb that really fits my requests and thank you for providing such useful tool.
I have to run it in x86-32 and arm32 platform. To be honest, I am not familiar to CMAKE.
If it is possible, could you please provide some examples or any information showing how to compile it for x86-32 and arm32 platform.

**Comment by katyo** [comment]
@AngusWooster I think it quite easy. You need setup environment variables to use appropriate toolchain (CC=arm-***eabi-**cc, AR=arm-**ar, and etc.). In case of cmake you can also use its toolchain configs (see https://cmake.org/cmake/help/v3.14/manual/cmake-toolchains.7.html)

**Comment by AngusWooster** [comment]
@katyo 
I appreciate your reply. This information is very useful for me.
Thank you
