### ISSUE TITLE
EJDB Option

### ISSUE THREAD

**Issue by AngusWooster** [Softmotions/ejdb#286]
There are two elements "sort_buffer_sz" and "document_buffer_sz" in EJDB_OPTS.
If  **sort_buffer_sz** and **document_buffer_sz** set as minimum

What impact does it have for different size setting?

**Comment by adamansky** [comment]
Good day @AngusWooster!
`document_buffer_sz` - It is a temporal buffer used to store documents during query processing. Ideally should be maximum size of document (in binn format) scanned by query. It will be reallocated on demand.

` sort_buffer_sz` - Maximum size of in-memory buffer used to sort documents in queries with `order by` clause. If exceeds, a temp file will be created on disk to sort data.
