### ISSUE TITLE
How do you check for null or exists in jql?

### ISSUE THREAD

**Issue by markwylde** [Softmotions/ejdb#290]
I can query records that only have a field. For example `firstName`.

But can I check for fields that do not have `firstName`?

```javascript
// Will return only records that have a firstName
const q = db.createQuery(`/firstName`, 'messages');
```

I have tried the following but none work. I've also looked at the [test cases](https://github.com/Softmotions/ejdb/blob/master/src/jql/tests/jql_test1.c) but maybe there isn't one or I'm missing it?

Thanks

**Comment by adamansky** [comment]
It can be achieved by following:
```js
const q = db.createQuery(`/* and not /firstName`, 'messages');
```

**Comment by markwylde** [comment]
Worked perfectly. Thanks @adamansky.
