### ISSUE TITLE
Indexing problem or misunderstanding?

### ISSUE THREAD

**Issue by markwylde** [Softmotions/ejdb#291]
Another project:
https://github.com/markwylde/ejdb-stressed

So my aim was to try and create a 1GB file and see what performance was like.

Without any indexes it was only taking a few seconds to query. Which is amazing. I'm sure it would start to slow down at some bigger complex querying.

But, I started looking at implementing indexes, but I think there may be a bug.

## What am I doing?
In the project above you can see I've added two indexes:

```javascript
await db.ensureStringIndex('messages', '/firstName', false);
await db.ensureStringIndex('messages', '/lastName', false);
```

Step 1) I run the seeder `node ./lib/seeder` for about 10 seconds then ctrl+x. You'll see a load of numbers. This emits every time I insert a person with the last name "Black". In my test I had 25.

Step 2) I run the query `node ./lib/query` and instantly get only 5 results back. (There should be 25)

I should note, without indexes this is fine.

## Notes
- Each time I run my script it's inconsistent. Sometimes I will get 0 results, sometimes a couple, sometimes 10. But never all of them.
- I always get a lot of records when I run `const q = db.createQuery(`/*`, 'messages');`
- Since I hard close the seeder after a few seconds, maybe the index isn't getting time to build. But I would have thought it would recover when it next starts?
- But even if I close the application gracefully, it still doesn't have all the records

Sorry if this is a bit long or if I'm missing something obvious. I'm happy to adjust my tests and try things out if it helps. Or hopefully I've just missed something in the docs, and you can point me to it and solved! 👍 

Thanks again

**Comment by adamansky** [comment]
Hi Mark! Thank you a lot! You are lucky guy - you have found a quite serious bug passed through our test cases. I've released updates including nodejs binding.

Just upgrade `ejdb2_node` to `v1.0.42 ` and all should be ok.

PS.
* Please use `await db.put('messages', record);`  because `db.put` returns a Promise so `db.put('message', record, function(...))` makes no sense. 
* Another point you don't need to stringify `record` object just pass it to `db.put`

Here is the modified seeder I've used for testing:
```js
const chance = new require('chance')();
const uuid = require('uuid').v4;
const { EJDB2 } = require('ejdb2_node');
const fs = require('fs');
const util = require('util');

const appendFile = util.promisify(fs.appendFile);

async function run() {
  const db = await EJDB2.open('./example.db', {
    truncate: true
  });

  await db.ensureStringIndex('messages', '/firstName', false);
  await db.ensureStringIndex('messages', '/lastName', false);

  let black = 0;
  async function batch (number) {
    for (var i = 0; i < number; i++) {
      const id = uuid();
      const lastName = chance.last();
      const record = {
        id,
        firstName: chance.first(),
        lastName,
        email: chance.email(),
        content: chance.paragraph({ sentences: 1 })
      }

      if (lastName === 'Black') {
        ++black;
      }

      await db.put('messages', record);
      await appendFile('data.txt', `${JSON.stringify(record)}\n`);

    }
  }

  await batch(20000);

  console.log(`Number of black ${black}`);

  await db.close();
}

run();
```

Feel free to reopen issue.
