### ISSUE TITLE
J-server Server returned nothing (no headers, no data)

### ISSUE THREAD

**Issue by AngusWooster** [Softmotions/ejdb#300]
Hi EJDB contributor
Thanks for providing J-server which is convenient for integrating.
I have used J-server in my project for a long time and it looks very thing fine
My environment is arm-32 bit and using CURL to communicate with J-server.
Yesterday I got a error when I send a http post by CURL to J-server.
The error message is "curl_easy_perform curlrc = 52, failed: Server returned nothing (no headers, no data)."
It seems that libcurl didn't receive any response from the server after it sent off its request.

Could you please give me some advice? This issue can't be reproduced easily.

**Comment by adamansky** [comment]
Hi! I can't help here since lack of information. You can get stdout/stderr messages if they present, attach to the process by `gdb` then get stack threads traces and it may help somehow. Turn on verbose mode for curl, try to test endpoint by `wscat`,

**Comment by AngusWooster** [comment]
I appreciate your advice.
Many Thanks
