### ISSUE TITLE
java.util.concurrent.RejectedExecutionException

### ISSUE THREAD

**Issue by seanradford** [Softmotions/ejdb#305]
Hi,

I'm investigating the use of EJDB2 within a Flutter app (it looks great by the way).

When I try to seed using a list of around 100 objects without waiting for each to complete, e.g.

```
List listOfJsonObjects = ...;
listOfJsonObjects.forEach((json) => db.put(collectionName, json);
```
I seen numerous errors (around 30 of the puts fail), e.g.

`E/Ejdb2FlutterPlugin(24633): Task com.softmotions.ejdb2.-$$Lambda$Ejdb2FlutterPlugin$qFdyIL_dBCp3asLJEc2Dijue1Cg@bc75166 rejected from java.util.concurrent.ThreadPoolExecutor@860a8e8[Running, pool size = 5, active threads = 5, queued tasks = 0, completed tasks = 1564]
E/Ejdb2FlutterPlugin(24633): java.util.concurrent.RejectedExecutionException: Task com.softmotions.ejdb2.-$$Lambda$Ejdb2FlutterPlugin$qFdyIL_dBCp3asLJEc2Dijue1Cg@bc75166 rejected from java.util.concurrent.ThreadPoolExecutor@860a8e8[Running, pool size = 5, active threads = 5, queued tasks = 0, completed tasks = 1564]`

I'm presuming from the error message that this is due to thread pool exhaustion? I can prevent this by waiting for each put to complete before proceeding to perform the next one - which in this case is fine. But may not be a full solution as part of a whole application. Therefore is there anything else that I can do to prevent or mitigate this? Can the thread pool size be increased (would that even help)?

My additional thought with regards to usage of EJDB is to 'wait' where possible, and additionally wrap calls in a retry, explicitly catching the above to attempt a maximum number of times before failing.

Would appreciate any thoughts. Thanking you in advance.

**Comment by adamansky** [comment]
Sorry for e long delay fixed it and updated flutter package `ejdb2_flutter: ^2.62.2` It should be ok now
