### ISSUE TITLE
Binding error logging

### ISSUE THREAD

**Issue by markwylde** [Softmotions/ejdb#307]
Hi

The following message appears when starting an existing database.

> 23 Feb 19:31:13.304 WARN iwal.c:547: Database recovered at point of time: 1614072651099 ms since epoch

Is there a way we can capture these messages?

For example:

```javascript
const db = await EJDB2.open("example.db");
db.on('warn', message => {
  console.log('got a warn, message)
})
```

or

```javascript
const db = await EJDB2.open("example.db", {
  logger: {
    warn: message => {
      console.log('got a warn, message)
    }
  }
})
```

**Comment by adamansky** [comment]
Hi Mark! 
This message appeared when database is not closed before nodejs process exits. 
This messages reported directly to `stderr` from c libary, so it will be problematic to redirect it to specific callback fn.
