### ISSUE TITLE
How to reclaim data file after deleting rows data?

### ISSUE THREAD

**Issue by showapicxt** [Softmotions/ejdb#309]
I found that after  deleting  rows data, the db file space is not recycled. How can I reclaim the data file? or  dump old to new file?  thank you .

**Comment by adamansky** [comment]
Hi! Yes, if you delete some of documents physically located at end of file then the data file will shrink automatically. Free space areas in somewhere in file is reused for new records. The only way to compact database file is to backup data then recreate all records from scratch.
