### ISSUE TITLE
Escaping

### ISSUE THREAD

**Issue by markwylde** [Softmotions/ejdb#322]
Hi @adamansky 

I have come across a weird one.

Let's say I have the following document in my ejdb database:
```json
{
  "foo[bar": "baz"
}
```

Now I want to query that document on it's only property.

```
/[foo[bar] = :?]
     ^ note, this character is actually in the key name
```

This does (as it should do) cause an error:

```
Error: 
/a\[ <--- 
```

Is there a way of escaping characters in the jql?

For example:

```
/[foo\[bar] = :?]
     ^ note, the backslash indicates an escape of the proceeding character
```

I've had a look through the tests and docs, but I am sorry if this has already been answered.

Thanks for everything as always!

**Comment by adamansky** [comment]
Hi Mark! Double quotes should help here:
```
/["foo[bar" = :?]
```

**Comment by adamansky** [comment]
Moreover  string in quotes parsed as JSON string so you can use `\'` `\"` `\n` symbols here

**Comment by markwylde** [comment]
Excellent as always @adamansky . Thanks so much. It's working perfectly:
https://github.com/markwylde/mql-to-jql/pull/7
