### ISSUE TITLE
How Do I Release Disk Space After Deleting a Database?

### ISSUE THREAD

**Issue by WhiteSauerkraut** [Softmotions/ejdb#344]
After data is deleted from the database, for example, the number of data records in the database is deleted from 10000 to 0, but the disk usage of the database remains unchanged. I'm looking forward to your reply, thank you.

```c++
    std::string delSql = "xxx";
    JQL q = 0;
    iwrc rc = jql_create(&q, coll, delSql.c_str());
    RCGO(rc, FINISH);

    EJDB_EXEC ux;
    ux.cnt = 0;
    ux.db = db_;
    ux.limit = 0;
    ux.log = 0;
    ux.opaque = 0;
    ux.pool = 0;
    ux.q = q;
    ux.skip = 0;
    ux.visitor = 0;
    rc = ejdb_exec(&ux);
    RCGO(rc, FINISH);
FINISH:
    if (q) {
        jql_destroy(&q);
    }
    if (rc != 0) {
        iwlog_ecode_error3(rc);
        ...
    }

**Comment by WhiteSauerkraut** [comment]
anyone can help？

**Comment by adamansky** [comment]
Hi! Data are placed in a single file, so if you delete some data and data is located somewhere in the middle of db file - file will not be truncated. If data from the end of file will be removed - file size will be reduced. If you delete all collections from db, file will be truncated too.

**Comment by WhiteSauerkraut** [comment]
thank you bro, thank you very much for your answer, I will try again.
