### ISSUE TITLE
if the db is large, it will take large memory after query db

### ISSUE THREAD

**Issue by blueshame** [Softmotions/ejdb#350]
- first step: I make EJDB db file reach 496M, each record size is 512K, and 1,000,000 record in the db file.  there is no index. the record like this: {'name":xxx, "type":xxx, "time":xxxx, "pid":xxx, "tid":xxxx, "uid":xxx, "key1":..., ..}, about 15 field.

- second step: I write query code to search record from db. the condition is very easy.  /[ name = xxx ].  It take 1 second to get result. but the meomry is vary large. I run showmap to check memory. the PSS of process nearly 500M.  the most memory is the db file. I guess ejdb    load the whole file to memory. Is there any way to optimize the meomory of EJDB?

- the PSS of db file when query
![image](https://user-images.githubusercontent.com/4469977/186874936-31a92cc4-a9a3-4cdd-90f6-9b46d6930b76.png)

**Comment by blueshame** [comment]
> Ejdb [mmaps](https://man7.org/linux/man-pages/man2/mmap.2.html) your `/data/test/rawejdb.db` into virtual address space of your program. So this memory pages are cached by OS and actually are not reside in physical RAM.

Do you means this memory cached?
![image](https://user-images.githubusercontent.com/4469977/186883371-2185aead-ef2a-45e0-997d-0e275a2f5c1e.png)

**Comment by adamansky** [comment]
I mean what you show me is the result of memory mapping of the database file into virtual OS memory.
You may show me some numbers for sample program which creates a quite big file filled by random numbers, then do mmap on this file, then read it all by mmap pointer.

**Comment by blueshame** [comment]
> I mean what you show me is the result of memory mapping of the database file into virtual OS memory. You may show me some numbers for sample program which creates a quite big file filled by random numbers, then do mmap on this file, then read it all by mmaped pointer.

I run this command why the memory does not decrease
` shell
echo 1 > /proc/sys/vm/drop_caches
`
