### ISSUE TITLE
Why Is the INT64_MIN Displayed with Garbled Characters?

### ISSUE THREAD

**Issue by WhiteSauerkraut** [Softmotions/ejdb#352]
The INT64_MIN is stored in the database. After the INT64_MIN is read, garbled characters are displayed.
--save data：
{"KEY_INT64_MIN":-9223372036854775808}
--read data：
{"KEY_INT64_MIN":-'..--).0-*(+,))+(0(}

**Comment by adamansky** [comment]
Hi! It seems to be a bug. Will investigate it.

**Comment by WhiteSauerkraut** [comment]
> Hi! It seems to be a bug. Will investigate it.

OK, look forward to your bug fix.

**Comment by adamansky** [comment]
Fixed by https://github.com/Softmotions/iowow/commit/6b5b29ac225e3e0afb78a0d390b479a38e78442b

Clean ejdb build from master branch should contains this fix
