### ISSUE TITLE
Windows cross compile issue

### ISSUE THREAD

**Issue by OliHip** [Softmotions/ejdb#359]
Hi all, 

I would like to cross compile ejdb for windows since Ubuntu. 
I followed the guide  https://github.com/Softmotions/ejdb/blob/master/WINDOWS.md. 
But at this step : >> make package

I've got this error:

http://softmotions.com/windev/lib.exe:
2022-10-17 15:39:17 erreur 403 : Forbidden.
make[2]: *** [src/CMakeFiles/wintools_init.dir/build.make:75 : WINTOOLS/lib.exe] Erreur 8
make[2]: *** Suppression du fichier « WINTOOLS/lib.exe »
make[1]: *** [CMakeFiles/Makefile2:197 : src/CMakeFiles/wintools_init.dir/all] Erreur 2
make: *** [Makefile:156 : all] Erreur 2

How can I solve this issue ? 
Thanks in advance.

**Comment by adamansky** [comment]
Fixed in master, thank you. Please reopen if your issue will remain
