### ISSUE TITLE
it's better delete temp file after use it

### ISSUE THREAD

**Issue by blueshame** [Softmotions/ejdb#367]
I found so many temp file under /tmp. Some of them are very big and will take so much space. So it's better to remove it after use it

![image](https://user-images.githubusercontent.com/4469977/202452269-a060254f-08d9-4cec-a280-92323e40bf09.png)

**Comment by adamansky** [comment]
Files are deleted actually https://github.com/Softmotions/ejdb/blob/master/src/jbi/jbi_sorter_consumer.c#L161 but only if database process not crashed before. So here you have a sorting files remain after crash due to #366
