### ISSUE TITLE
Windows cross compilation trouble

### ISSUE THREAD

**Issue by IsraelDragone** [Softmotions/ejdb#375]
I'm trying to make a windows cross-compilation from Debian 10, using MXE, and I'm having some issues in the cmake process. I received this message: Configuring incomplete, errors occurred! Plus an indication to look in the cmake log files, but I didn't find any clue of what could happen there. 

I was able to compile the version in the winode branch, the cmake goes clean, and I have some issues that I could fix in the making process and also make the c# biding, but this branch is out-to-date (last commit in 2019) and some functions aren't available there. 

So if anyone could give me some light I will be very thankful!

**Comment by adamansky** [comment]
Thanks! Checking what

**Comment by adamansky** [comment]
Hi! Although fixes I've made are not directly related to your issue Windows build is ok for now.

```sh
git pull
git submodules update
rm -rf ./build/*

# Then follow the guide in WINDOWS.md
``` 

Just tested it on Ubuntu 22.04, all is ok

**Comment by adamansky** [comment]
Please reopen it if the issue is still persists
