### ISSUE TITLE
CMake Minimum Version

### ISSUE THREAD

**Issue by markwylde** [Softmotions/ejdb#377]
Hey, just noticed a problem with the version of cmake I use:
```
build$ cmake .. -DBUILD_NODEJS_BINDING=ON -DCMAKE_BUILD_TYPE=Release
CMake Error at CMakeLists.txt:3 (cmake_policy):
  Policy "CMP0135" is not known to this version of CMake.
```

In the readme we state:
`cmake v3.12 or higher required`

But I use:
`cmake version 3.22.1`
and
`v3.23.0-rc3`

Looks like the [latest version](https://github.com/Kitware/CMake/releases) is:
`v3.25.2`

If you mean to increase the minimum version required of CMake, should we update the docs?

**Comment by adamansky** [comment]
Hi Mark! I've added this policy in order to eliminate annoying warning concerning timestamps of downloaded subproject artifacts. As you seen I've introduced another warning for older versions. I may add `if` for cmake version around this policy setup but is it worth it?

**Comment by markwylde** [comment]
Yeah, for me I'd probably just update the README to be greater than version 3.25. Probably better to be on the latest version, and saves putting a bunch of if's over the place.

But either way is cool. It was easy updating my scripts to use the latest version, so it seems to be well available.
