### ISSUE TITLE
use ejdbv2.73 in C++, but complie error

### ISSUE THREAD

**Issue by blueshame** [Softmotions/ejdb#381]
![image](https://user-images.githubusercontent.com/4469977/227080551-66e689af-735a-417a-a423-f4e246a2f8c1.png)

I use ejdbv.273 in C++, but meet these problem

**Comment by markwylde** [comment]
Hey, I'm not very good at C++ but I do build ejdb using CI/CD pipelines and the latest version seems to be building fine for me.

Can you recreate it in a simple, standalone project?

What version of cmake are you using?

What c++ compiler are you using?

Can you list any other versions of stuff in your toolstack, like the OS version.

**Comment by adamansky** [comment]
> ![image](https://user-images.githubusercontent.com/4469977/227080551-66e689af-735a-417a-a423-f4e246a2f8c1.png)
> 
> I use ejdbv.273 in C++, but meet these problem

Hi! Sure will fix it tomorrow, sorry C++ is very different from C and sometimes we have suchlike issues.

**Comment by adamansky** [comment]
Fixed, all should be okay in master branch. Full clean rebuild is required. Please reopen this issue if any problems with C++.
