### ISSUE TITLE
Synchronization / copying

### ISSUE THREAD

**Issue by Ivshti** [Softmotions/ejdb#69]
It would be great if EJDB featured an ability to "synchronize" to a remote database (with conflict resolution).
This would mean that both the remote and local databases would be writable, and upon sync , the changes would be merged. A conflict would arise if one document (object) was modified in both databases before sync, in which case the resolution would depend on the implementation.

I imagine the API to be something like:
.sync(cname, remoteURI, function conflictRes(one, two), function callback())

Hidden keys like "_mtime" and "_rev" would have to be introduced in order to implement this.

**Comment by adamansky** [comment]
Closed in favour to ejdb 2.0 https://github.com/Softmotions/ejdb/blob/master/README.md
