### ISSUE TITLE
Support of wildcard operator "*"

### ISSUE THREAD

**Issue by koskokos2** [Softmotions/ejdb#95]
Is it possible to implement support of "*" in $fields to match all indexes in array?
- Example 1: 
  Using this in fields is very needed in case you do not know size of array or sizes for each document can be different.
  -- Data:
  "array" : [ { "a" : "b", "c" : "d" } , { "e" : "f" } ]
  -- Query $fields:
  "$fields" : { "array.*_.c" : "1", "array._.e" : "1" }
  -- Result:
  "array" : [ { "c" : "d" } , { "e" : "f" } ]
- Example 2: 
  Another place where operator "_" support will be convenient is alternative way of $elemMatch:
  -- Current way:
  "array" : { "$elemMatch" : { "a" : "b" } }
  -- Alternative way:
  "array._*.a" : "b"

**Comment by kkk777kkk** [comment]
my solution http://pastebin.com/tbHARU8x

**Comment by tyutyunkov** [comment]
Thank you Kostyantyn for your solution! But, this solution doesn't work with nested arrays (a8ae6df7b8047130c50b10fb0475b1a9742d0461). Could you fix it?

**Comment by adamansky** [comment]
Closed in favour to ejdb 2.0 https://github.com/Softmotions/ejdb/blob/master/README.md
